const GETREQUEST = "GETREQUEST";
const GETSUCCESS = "GETSUCCESS";
const GETFAILURE = "GETFAILURE";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
const GET_PROPERTIES_FAILURE = "GET_PROPERTIES_FAILURE";

const POST_PROPERTY_REQUEST = "POST_PROPERTY_REQUEST";
const POST_PROPERTY_SUCCESS = "POST_PROPERTY_SUCCESS";
const POST_PROPERTY_FAILURE = "POST_PROPERTY_FAILURE";

const SEARCH_PROPERTIES_REQUEST = "SEARCH_PROPERTIES_REQUEST";
const SEARCH_PROPERTIES_SUCCESS = "SEARCH_PROPERTIES_SUCCESS";
const SEARCH_PROPERTIES_FAILURE = "SEARCH_PROPERTIES_FAILURE";

const GET_PROPERTY_BY_ID_REQUEST = "GET_PROPERTY_BY_ID_REQUEST";
const GET_PROPERTY_BY_ID_SUCCESS = "GET_PROPERTY_BY_ID_SUCCESS";
const GET_PROPERTY_BY_ID_FAILURE = "GET_PROPERTY_BY_ID_FAILURE";

const GET_PROFILE = "GET_PROPERTY_BY_ID_REQUEST";
const GET_PROFILE_SUCCESS = "GET_PROPERTY_BY_ID_SUCCESS";
const GET_PROFILE_FAILURE = "GET_PROPERTY_BY_ID_FAILURE";

export {
    GET_PROPERTY_BY_ID_FAILURE,GET_PROPERTY_BY_ID_SUCCESS,GET_PROPERTY_BY_ID_REQUEST,SEARCH_PROPERTIES_FAILURE ,
    SEARCH_PROPERTIES_SUCCESS ,SEARCH_PROPERTIES_REQUEST ,
    GETREQUEST, GETSUCCESS, GETFAILURE, 
    GET_PROPERTIES_REQUEST, GET_PROPERTIES_SUCCESS, GET_PROPERTIES_FAILURE,
    POST_PROPERTY_REQUEST, POST_PROPERTY_SUCCESS, POST_PROPERTY_FAILURE ,  LOGIN_REQUEST,
    LOGIN_SUCCESS,GET_PROFILE,GET_PROFILE_SUCCESS,GET_PROFILE_FAILURE,
    LOGIN_FAILURE
};
